### PR TITLE
Lambda support

### PR DESCRIPTION
**Pull request by prodion23**
## Description
Adds lambda instrumentation support - AWS_LAMBDA_EXEC_WRAPPER is available for the 3 lambda node runtimes, so the same approach will work across all of them.

### CODE REVIEW

**Comment by prodion23** [comment]
Need to investigate why lambda spans aren't getting recycled after the lambda tests run - will resolve tomorrow AM.

**Comment by tim-mwangi** [comment]
@prodion23 you have not run into the Centos 8 issue due to it's EOL?

**Comment by prodion23** [comment]
@tim-mwangi hmm, I have not seen issue with centos:8 - is it being referenced in this repo somewhere? 
(I think ctrl+f may not be finding it?)

**Comment by tim-mwangi** [comment]
> @tim-mwangi hmm, I have not seen issue with centos:8 - is it being referenced in this repo somewhere? (I think ctrl+f may not be finding it?)

I think it's fine for HT nodejsagent since it's not building anything native.

**Review by tim-mwangi — APPROVED** [review]

**Review by tim-mwangi — APPROVED** [review]

**Pull request merged**
